---
- hosts: malfoy
  vars:
    app_path: /app/corganize
    config_dir: "{{ app_path }}/mnt/data/diffusion"
    config_path: "{{ config_dir }}/config.json"
    img_dir: "{{ app_path }}/mnt/data/images"
  tasks:
    - name: Ensure git is installed
      package:
        name: git
        state: present
    - name: Checkout the code base
      git:
        repo: https://github.com/jaeseopark/corganize.git
        dest: "{{ app_path }}"
        version: master  # Specify branch/tag/commit
        update: yes  # Pull changes if the repo already exists
    - name: Ensure Docker Compose is stopped
      community.docker.docker_compose:
        project_src: "{{ app_path }}"
        state: absent
    - name: Ensure folder(s) exists
      file:
        path: "{{ item }}"
        mode: u=rwx,g=rwx,o=rx
        state: directory
      loop:
      - "{{ config_dir }}"
      - "{{ img_dir }}"
    - name: Copy config file from the master node
      template:
        src: corganize.config.txt
        dest: "{{ config_path }}"
    - name: Ensure Docker Compose is running
      community.docker.docker_compose:
        project_src: "{{ app_path }}"
        state: present
        build: true
        pull: true
