---
- hosts: malfoy
  vars:
    app_path: /app/corganize-server
    db_path: "{{ app_path }}/mnt/db"
    log_path: "{{ app_path }}/mnt/log"
  tasks:
    - name: Ensure git is installed
      package:
        name: git
        state: present
    - name: Ensure folder(s) exists
      file:
        path: "{{ item }}"
        mode: u=rwx,g=rwx,o=rx
        state: directory
      loop:
      - "{{ app_path }}"
      - "{{ db_path }}"
      - "{{ log_path }}"
    - name: Ensure Docker Compose is stopped
      community.docker.docker_compose_v2:
        project_src: "{{ app_path }}"
        state: absent
    - name: Copy compose file from the master node
      template:
        src: corganize-server.docker-compose.j2
        dest: "{{ app_path }}/docker-compose.yml"
    - name: Ensure Docker Compose is running
      community.docker.docker_compose_v2:
        project_src: "{{ app_path }}"
        build: always
