---
- hosts: malfoy
  vars:
    app_path: /app/corganize-daemon
    docker_compose_path: "{{ app_path }}/docker-compose.yml"
    env_path: "{{ app_path }}/.env"
    data_path: /mnt/crg/data
    log_path: "{{ app_path }}/mnt/log"
  tasks:
    - name: Ensure folders exists
      file:
        path: "{{ item }}"
        mode: u=rwx,g=rwx,o=rx
        state: directory
      loop:
      - "{{ app_path }}"
      - "{{ log_path }}"
    - name: Copy creds from the master node
      copy:
        src: corganize-daemon.env.j2
        dest: "{{ env_path }}"
    - name: Ensure the creds file exists
      file:
        path: "{{ env_path }}"
        state: file
    - name: Copy config file from the master node
      template:
        src: corganize-daemon.docker-compose.j2
        dest: "{{ docker_compose_path }}"
    - name: Ensure Docker Compose is stopped
      community.docker.docker_compose:
        project_src: "{{ app_path }}"
        state: absent
    - name: Ensure Docker Compose is running
      community.docker.docker_compose:
        project_src: "{{ app_path }}"
        state: present
        pull: true
