---
- hosts: malfoy
  vars:
    app_path: "/app/paperless"
    local_mount_path: "{{ app_path }}/mnt"
    docker_compose_path: "{{ app_path }}/docker-compose.yml"
    env_file_path: "{{ app_path }}/paperless.env"
  tasks:
    - name: Ensure folders exists
      file:
        path: "{{ item }}"
        mode: u=rwx,g=rwx,o=rx
        state: directory
      loop:
      - "{{ app_path }}"
      - "{{ local_mount_path }}"
    - name: Copy config file from the master node
      template:
        src: paperless.docker-compose.j2
        dest: "{{ docker_compose_path }}"
    - name: Copy environment file from the master node
      template:
        src: paperless.env
        dest: "{{ env_file_path }}"
    - name: Ensure Docker Compose is stopped
      community.docker.docker_compose_v2:
        project_src: "{{ app_path }}"
        state: absent
    - name: Ensure Docker Compose is running
      community.docker.docker_compose_v2:
        project_src: "{{ app_path }}"
        state: present
        pull: missing
