# Tested on Rpi 4B+ Debian 12
---
- hosts: webcampi
  become: yes  # Enable sudo
  vars:
    build_path: /apps/v4l2rtspserver
    executable_path: /usr/local/bin/v4l2rtspserver
    service_config_path: /etc/systemd/system/v4l2rtspserver.service
    video_device: /dev/video0 # TODO: automate v4l2-ctl --list-devices
  tasks:
    - name: utility present
      package:
        name: [ "git", "cmake", "liblog4cpp5-dev", "libv4l-dev" ]
        state: present
    - name: Check if the file exists
      stat:
        path: /usr/local/bin/v4l2rtspserver
      register: rtspserver_status
    - name: Clone the source repository
      when: not rtspserver_status.stat.exists
      git:
        repo: https://github.com/mpromonet/v4l2rtspserver.git
        dest: "{{ build_path }}"
    - name: Build from source
      when: not rtspserver_status.stat.exists
      command: |
        cmake .
        make
        make install
      args:
        chdir: "{{ build_path }}"
    - name: Copy service config file
      template:
        src: v4l2rtspserver.service.j2
        dest: "{{ service_config_path }}"
    - name: Enable v4l2rtspserver service at boot
      systemd:
        name: v4l2rtspserver
        enabled: yes
        state: started
        daemon_reload: yes
