version: "3.6"
services:
  homer:
    container_name: homer
    hostname: homer
    image: b4bz/homer:latest
    restart: unless-stopped
    ports:
      - 80:8080
    volumes:
      # :ro for read-only
      - ./img:/www/assets/img:ro
      - ./config.yml:/www/assets/config.yml:ro
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "805:80/tcp"
    environment:
      TZ: 'America/Chicago'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './pihole-mnt/etc-pihole/:/etc/pihole/'
      - './pihole-mnt/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  ui:
    container_name: mlib-ui
    image: jaeseoparkdocker/mlib-ui:latest
    ports:
      - 4534:80
