---
- hosts: vpnservers
  vars:
    apps:
      - name: jellyfin
        ip: "{{ hostvars[jellyfin_host].wg_ip }}"
        port: "{{ jellyfin_port }}"
      - name: paperless
        ip: "{{ hostvars[paperless_host].wg_ip }}"
        port: "{{ paperless_port }}"
        additional_config: client_max_body_size 1024m;
      - name: radarr
        ip: "{{ hostvars[arr_host].wg_ip }}"
        port: "{{ radarr_port }}"
      - name: sonarr
        ip: "{{ hostvars[arr_host].wg_ip }}"
        port: "{{ sonarr_port }}"
      - name: lidarr
        ip: "{{ hostvars[arr_host].wg_ip }}"
        port: "{{ lidarr_port }}"
      - name: prowlarr
        ip: "{{ hostvars[arr_host].wg_ip }}"
        port: "{{ prowlarr_port }}"
      - name: homeassistant
        ip: "{{ hostvars[homeassistant_host].wg_ip }}"
        port: "{{ homeassistant_port }}"
      - name: corganize
        ip: "{{ hostvars[corganize_host].wg_ip }}"
        port: "{{ corganize_port }}"
      - name: wiki
        ip: "{{ hostvars[wiki_host].wg_ip }}"
        port: "{{ wiki_port }}"
        additional_config: client_max_body_size 50m;
      - name: bobbins
        ip: "{{ hostvars[bobbins_host].wg_ip }}"
        port: "{{ bobbins_port }}"
      - name: divvy
        ip: "{{ hostvars[divvy_host].wg_ip }}"
        port: "{{ divvy_port }}"
        additional_config: client_max_body_size 50m;
  tasks:
    - name: Ensure nginx is installed
      package:
        name: nginx
        state: present
    - name: Ensure nginx is not running
      service:
        name: nginx
        state: stopped
    - name: Copy nginx config from the host manchine
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-enabled/default.conf
    - name: start nginx
      service:
        name: nginx
        state: started
