---
- name: start homer
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}"
    state: present

- name: stop homer
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}"
    state: absent
  when: clean_restart | default(false)
