- name: Determine corganize server target host
  hosts: localhost
  vars:
    app_name: corganize-server
  roles:
    - dynamic_host_resolver

- name: Deploy corganize application
  hosts: resolved_host
  vars:
    app_path: /app/corganize-server
    restic_repository_name: "corganize/server"
    branch: "master"
  roles:
    - corganize-server
    - restic
