- name: Determine corganize web client target host
  hosts: localhost
  vars:
    app_name: corganize
  roles:
    - dynamic_host_resolver

- name: Deploy corganize web client
  hosts: resolved_host
  vars:
    app_path: /app/corganize-web # app path uses the "-web" suffix
    data_mnt_path: "/mnt/crg"
    branch: "master"
  roles:
    - corganize
