---
- name: Setup a Mac host
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    automator_path: "~/Automator"
    automator_source_path: "{{ automator_path }}/.source"
  roles:
    - automator_fish_perfect
    - automator_rota_fix
    - mac_apps
    - mac_shell_aliases
    - mac_dns
    - mac_dock
    - mac_safari
    - mac_keyboard
    - mac_barrier
    - mac_orcaslicer
    - mac_forklift
