- name: Paperless
  hosts: paperless # To change deploy host, change inventory.ini.
  vars:
    app_path: "/app/paperless"
    local_mount_path: "{{ app_path }}/mnt"
    restic_repository_name: "paperless"
    restic_backup_paths:
      - src: "{{ local_mount_path }}"
        target: /backup
  roles:
    - paperless
    - restic-backup

- name: Webcam
  hosts: webcam
  become: true
  roles:
    - webcam
