---
- hosts: prd
  vars:
    app_path: /app/paperless
    local_mount_path: /app/paperless/mnt
    watch_path: /mnt/svc/paperless/watch
    docker_compose_path: /app/paperless/docker-compose.yml
    env_file_path: /mnt/svc/paperless/paperless.env
  tasks:
    - name: Ensure folders exists
      file:
        path: "{{ item }}"
        mode: u=rwx,g=rwx,o=rx
        state: directory
      loop:
      - "{{ app_path }}"
      - "{{ local_mount_path }}"
      - "{{ watch_path }}"
    - name: Copy config file from the master node
      template:
        src: paperless.docker-compose.j2
        dest: "{{ docker_compose_path }}"
    - name: Ensure Docker Compose is running
      community.docker.docker_compose:
        project_src: "{{ app_path }}"
        state: present
