---
- hosts: prd
  vars:
    app_path: /app/radarr
    mnt_path: "{{ app_path }}/mnt"
    docker_compose_path: "{{ app_path }}/docker-compose.yml"
    library_path: /mnt/media/movies
    download_dest_path: /mnt/media/media-downloads
  tasks:
    - name: Ensure folders exists
      file:
        path: "{{ item }}"
        mode: u=rwx,g=rwx,o=rx
        state: directory
      loop:
        - "{{ app_path }}"
        - "{{ mnt_path }}"
    - name: Copy config file from the master node
      template:
        src: radarr.docker-compose.j2
        dest: "{{ docker_compose_path }}"
    - name: Ensure Docker Compose is running
      community.docker.docker_compose:
        project_src: "{{ app_path }}"
        state: present
