---
- hosts: prd
  vars:
    app_path: /app/wiki
  tasks:
    - name: Ensure folders exists
      file:
        path: "{{ item }}"
        mode: u=rwx,g=rwx,o=rx
        state: directory
      loop:
      - "{{ app_path }}"
      - "{{ app_path }}/mnt"
      - "{{ app_path }}/mnt/wikijs-config"
      - "{{ app_path }}/mnt/wikijs-data"
    - name: Copy config file from the master node
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - src: wiki.docker-compose.j2
          dest: "{{ app_path }}/docker-compose.yml"
    - name: Ensure Docker Compose is stopped
      community.docker.docker_compose:
        project_src: "{{ app_path }}"
        state: absent
    - name: Ensure Docker Compose is running
      community.docker.docker_compose:
        project_src: "{{ app_path }}"
        state: present
        pull: true
