---
- hosts: bigboi
  vars:
    app_path: /app/jellyfin
    media_path: /mnt/media
    jellyfin_mnt_path: /app/jellyfin/mnt
    docker_compose_path: /app/jellyfin/docker-compose.yml
    tz: America/Denver
    puid: "0"
    pgid: "27"
  tasks:
    - name: Ensure folders exists
      file:
        path: "{{ item }}"
        mode: u=rwx,g=rwx,o=rx
        state: directory
      loop:
        - "{{ app_path }}"
        - "{{ jellyfin_mnt_path }}"
    - name: Ensure docker images are latest
      community.docker.docker_image:
        name: "{{ item }}"
        tag: latest
        source: pull
        state: present
      loop:
      - lscr.io/linuxserver/jellyfin
    - name: Ensure Docker Compose is not running
      community.docker.docker_compose_v2:
        project_src: "{{ app_path }}"
        state: absent
    - name: Copy compose file from the master node
      template:
        src: jellyfin-only.docker-compose.j2
        dest: "{{ docker_compose_path }}"
    - name: Ensure Docker Compose is running
      community.docker.docker_compose_v2:
        project_src: "{{ app_path }}"
        state: present