---
- hosts: machosts
  vars:
    - homebrewapps:
      - ansible
      - dockutil
    - caskapps:
      - orcaslicer
      - github
      - discord
      - visual-studio-code
      - autodesk-fusion
      - barrier
      - google-chrome
      - balenaetcher
      - db-browser-for-sqlite
      - firefox
      - licecap
  tasks:
    - name: Install Cask apps
      community.general.homebrew_cask:
        name: "{{ item }}"
      loop: "{{ caskapps }}"
    - name: Install Homebrew apps
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop: "{{ homebrewapps }}"
