---
- hosts: mac_hosts
  vars:
    ssl_path: ~/Library/Application Support/barrier/SSL
    pem_name: Barrier.pem
    clients: # displaynames of the clients
      - intuit
  tasks:
  - name: Ensure the SSL folder exists
    file:
      path: "{{ ssl_path }}"
      state: directory
  - name: Ensure the pem file exists
    command: "openssl req -x509 -nodes -days 365 -subj /CN=Barrier -newkey rsa:4096 -keyout {{ pem_name }} -out {{ pem_name }}"
    args:
      chdir: "{{ ssl_path }}"
      creates: "{{ ssl_path }}/{{ pem_name }}" # only execute the command if this file is not present.
  # TODO: restore configuration file
