- hosts: mac_hosts
  vars:
    docked_items:
      - /Applications/ForkLift.app/
      - /System/Applications/Utilities/Activity Monitor.app/
      - /Applications/Safari.app/
      - /System/Applications/Calendar.app/
      - /System/Applications/Mail.app/
      - /System/Applications/Photos.app/
      - /System/Applications/Reminders.app/
      - /System/Applications/Notes.app/
      - /System/Applications/Music.app/
      - /Applications/Barrier.app/
      - /Applications/Visual Studio Code.app/
      - /Users/jaeseopark/Library/Mobile Documents/com~apple~Automator/Documents/add-date-to-filename.app/
      - /Users/jaeseopark/Library/Mobile Documents/com~apple~Automator/Documents/generate-thumbs.app/
      - /Users/jaeseopark/Library/Mobile Documents/com~apple~Automator/Documents/merge-as-pdf.app/
      - /System/Applications/Messages.app/
      - /Applications/OrcaSlicer.app/
      - /Applications/Discord.app/
      - /Applications/Google Chrome.app/
      - /System/Applications/Utilities/Terminal.app/
      - /Users/jaeseopark/Applications/Autodesk Fusion.app
      - /Applications/GitHub Desktop.app/
      - /Applications/Reolink Client.app
      - /Applications/ChatGPT.app
  tasks:
  - name: Move dock to the left
    community.general.osx_defaults:
      domain: com.apple.dock
      key: orientation
      type: string
      value: left
  - name: Enable auto hide
    community.general.osx_defaults:
      domain: com.apple.dock
      key: autohide
      type: bool
      value: true
  - name: Eliminate auto hide delay
    community.general.osx_defaults:
      domain: com.apple.dock
      key: autohide-delay
      type: float
      value: 0
  - name: Remove auto hide time modiifer
    community.general.osx_defaults:
      domain: com.apple.dock
      key: autohide-time-modifier
      type: int
      value: 0
  - name: Empty the dock
    shell: "/opt/homebrew/bin/dockutil --remove all --no-restart" # skip restart until the end
  - name: Populate items
    shell: "/opt/homebrew/bin/dockutil --add '{{ item }}' --no-restart"
    loop: "{{ docked_items }}"
    ignore_errors: true
  - name: Add Desktop
    shell: "/opt/homebrew/bin/dockutil --add '~/Desktop' --view grid --display folder --sort dateadded --allhomes --no-restart"
  - name: Add Downloads
    shell: "/opt/homebrew/bin/dockutil --add '~/Downloads' --view grid --display folder --sort dateadded --allhomes"
