---
- hosts: machosts
  tasks:
  - name: Retrieve the user ID
    shell: |
        ls -d /path/to/parent/folder/*/ | xargs -n 1 stat --format '%Y %n' | sort -nr | head -n 1 | awk '{print $2}'
    register: folder_result