---
- hosts: machosts
  vars:
    remote_config_path: ~/Library/Application Support/OrcaSlicer/OrcaSlicer.conf
    download_path: orcaslicer/tmp_OrcaSlicer.conf
  tasks:
  - name: Load curated config content  
    include_vars:
      file: orcaslicer/OrcaSlicer.conf
      name: config
  - name: Download config file
    fetch:
        src: "{{ remote_config_path }}"
        dest: "{{ download_path }}"
        flat: yes
  - name: Load downloaded config content
    include_vars:
      file: "{{ download_path }}"
      name: downloaded_config
  - name: Save merged config as file
    copy:
      content: "{{ downloaded_config | combine(config, recursive=True) }}"
      dest: "{{ remote_config_path }}"
