---
docked_items:
  - /Applications/ForkLift.app/
  - /System/Applications/Utilities/Activity Monitor.app/
  - /Applications/Safari.app/
  - /System/Applications/Calendar.app/
  - /System/Applications/Mail.app/
  - /System/Applications/Photos.app/
  - /System/Applications/Reminders.app/
  - /System/Applications/Notes.app/
  - /System/Applications/Music.app/
  - /Applications/Barrier.app/
  - /Applications/Visual Studio Code.app/
  - /Users/jaeseopark/Library/Mobile Documents/com~apple~Automator/Documents/add-date-to-filename.app/
  - /Users/jaeseopark/Library/Mobile Documents/com~apple~Automator/Documents/generate-thumbs.app/
  - /Users/jaeseopark/Library/Mobile Documents/com~apple~Automator/Documents/merge-as-pdf.app/
  - /System/Applications/Messages.app/
  - /Applications/OrcaSlicer.app/
  - /Applications/Discord.app/
  - /Applications/Google Chrome.app/
  - /System/Applications/Utilities/Terminal.app/
  - /Users/jaeseopark/Applications/Autodesk Fusion.app
  - /Applications/GitHub Desktop.app/
  - /Applications/Reolink Client.app
  - /Applications/ChatGPT.app