---
- hosts: bigboi
  vars:
    app_path: /app/navidrome
    mnt_path: "{{ app_path }}/mnt"
    docker_compose_path: "{{ app_path }}/docker-compose.yml"
    library_path: /mnt/media/music
    # Computed navidrome app variables
    navidrome_app_object: "{{ apps | selectattr('name', 'equalto', 'navidrome') | first }}"
    navidrome_port: "{{ navidrome_app_object.port }}"
  tasks:
    - name: Ensure folders exists
      file:
        path: "{{ item }}"
        mode: u=rwx,g=rwx,o=rx
        state: directory
      loop:
        - "{{ app_path }}"
        - "{{ mnt_path }}"
    - name: Copy config file from the master node
      template:
        src: navidrome.docker-compose.j2
        dest: "{{ docker_compose_path }}"
    - name: Ensure Docker Compose is stopped
      community.docker.docker_compose:
        project_src: "{{ app_path }}"
        state: absent
    - name: Ensure Docker Compose is running
      community.docker.docker_compose:
        project_src: "{{ app_path }}"
        state: present
