---
title: "homelab"
subtitle: "192.168.86.232"
logo: "logo.png"

header: true
footer: false

theme: default
links: []

services:
  - name: "Self Hosted"
    icon: "fas fa-cloud"
    items:
      - name: "m9cad"
        logo: "assets/tools/m9cad.png"
        url: "http://192.168.86.232:3001/"
      - name: "Pi-hole"
        logo: "assets/tools/pihole.svg"
        url: "http://192.168.86.178:805/admin/"
      - name: "openmediavault"
        logo: "assets/tools/openmediavault.png"
        url: "http://192.168.86.179:80/"
      - name: "Kibana"
        logo: "assets/tools/elastic-kibana.svg"
        url: "#"
      - name: Grafana
        url: "http://192.168.86.232:3000"
        logo: assets/tools/grafana-icon.svg
      - name: Jupyter
        url: "http://192.168.86.232:8888"
        logo: assets/tools/jupyter.svg
  - name: "External"
    items:
      - name: "Grafana Hardware Dashboard"
        url: "https://jaeseopark.grafana.net/d/UDvWlpHnz/hardware"
        logo: "assets/tools/grafana-icon.svg"
      - name: "AWS Console"
        url: "https://console.aws.amazon.com/"
        logo: "assets/tools/aws-smile.png"
      - name: "Github"
        url: "https://github.com/jaeseopark?tab=repositories"
        logo: "assets/tools/github.png"
  - name: Kijiji
    items:
      - name: "Desktops under $200"
        url: "https://www.kijiji.ca/b-desktop-computers/edmonton/c772l1700203?price=__200"
        logo: assets/tools/kijiji.svg
