# This playbook was tested on Rpi 4B+ Debian 12
---
- name: Ensure required packages are present
  package:
    name:
      - git
      - cmake
      - liblog4cpp5-dev
      - libv4l-dev
    state: present

- name: Check if the v4l2rtspserver executable exists
  stat:
    path: "{{ executable_path }}"
  register: rtspserver_status

- name: Clone the source repository
  git:
    repo: https://github.com/mpromonet/v4l2rtspserver.git
    dest: "{{ build_path }}"
  when: not rtspserver_status.stat.exists

- name: Build from source
  command: |
    cmake .
    make
    make install
  args:
    chdir: "{{ build_path }}"
  when: not rtspserver_status.stat.exists

- name: Copy service config file
  template:
    src: v4l2rtspserver.service.j2
    dest: "{{ service_config_path }}"

- name: Enable v4l2rtspserver service at boot
  systemd:
    name: v4l2rtspserver
    enabled: yes
    state: started
    daemon_reload: yes

- name: Ensure startcam alias is present in bash profile
  lineinfile:
    path: ~/.bashrc
    regexp: '^alias startcam='
    line: 'alias startcam="sudo systemctl start v4l2rtspserver"'
    state: present

- name: Ensure stopcam alias is present in bash profile
  lineinfile:
    path: ~/.bashrc
    regexp: '^alias stopcam='
    line: 'alias stopcam="sudo systemctl stop v4l2rtspserver"'
    state: present

- name: Run stopcam command
  shell: source ~/.bashrc && stopcam
  args:
    executable: /bin/bash
