version: "3.6"

networks:
  loki:

services:
  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:8.1.5
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./grafana/bootstrap:/etc/grafana
      # - ./grafana/data:/var/lib/grafana
    networks:
      - loki
  loki:
    container_name: loki
    hostname: loki
    image: grafana/loki:2.3.0
    restart: unless-stopped
    ports:
      - 3100:3100
    networks:
      - loki
  promtail:
    container_name: promtail
    hostname: promtail
    image: grafana/promtail:2.3.0
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki
