---
cert_domain_groups: >-
  {%- set domain_groups = {} -%}
  {%- for app in (apps | default([]) | selectattr('deployed_domain', 'defined')) -%}
    {%- set base_domain = app.deployed_domain -%}
    {%- if base_domain not in domain_groups -%}
      {%- set _ = domain_groups.update({base_domain: [base_domain]}) -%}
    {%- endif -%}
    {%- set _ = domain_groups[base_domain].append(app.name + '.' + base_domain) -%}
  {%- endfor -%}
  {{ domain_groups }}
