version: '3.7'
services:
  jupyter:
    container_name: jupyter
    image: jupyter/scipy-notebook:latest
    ports:
    - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
    - ./data:/shared
