---
- name: Install Cask apps
  community.general.homebrew_cask:
    name: "{{ item }}"
  loop: "{{ caskapps }}"

- name: Install Homebrew apps
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrewapps }}"