---
- hosts: dev
  vars:
    dev_username: jaeseopark
    git_username: jaeseopark
    git_email: 20038316+jaeseopark@users.noreply.github.com
  tasks:
    - name: Ensure the dev user exists
      user:
        name: "{{ dev_username }}"
        shell: /bin/bash
        groups: sudo,docker
        append: yes
    - name: Ensure the docker repo file is absent before installing packages
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent
    - name: Install base packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - sudo
        - git
        - apt-transport-https
        - ca-certificates
        - lsb-release
        - gnupg
    - name: Set Git username
      community.general.git_config:
        name: user.name
        scope: system
        value: "{{ git_username }}"
    - name: Set Git email
      community.general.git_config:
        name: user.email
        scope: system
        value: "{{ git_email }}"
    - name: Add signing key for Docker
      apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present
    - name: Add Docker repository to sources list
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
    - name: Install Docker
      package:
        name: "{{ item }}"
        state: present
      loop:
        - docker
        - docker.io
        - docker-compose
        - docker-registry
    - name: Run Docker daemon
      service:
        name: docker.service
        state: started
        enabled: yes
