---
- hosts: vpnservers
  vars:
    apps:
      - name: jellyfin
        port: 8096
        ip: "{{ hostvars[jellyfin_host].wg_ip }}"
      - name: paperless
        port: 29743
        additional_config: client_max_body_size 1024m;
        ip: "{{ hostvars[paperless_host].wg_ip }}"
  tasks:
    - name: Ensure nginx is installed
      package:
        name: nginx
        state: present
    - name: Ensure nginx is not running
      service:
        name: nginx
        state: stopped
    - name: Copy nginx config from the host manchine
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-enabled/default.conf
    - name: start nginx
      service:
        name: nginx
        state: started
