---
- hosts: vpn
  vars:
    private_key_path: /etc/wireguard/private.key
    public_key_path: /etc/wireguard/public.key
    wg_conf_path: /etc/wireguard/wg0.conf
  tasks:
    - name: Ensure the required packages are installed
      package:
        name: "{{ item }}"
        state: present
      loop:
        - wireguard
        - ufw
    - name: Generate the private key file
      shell: "wg genkey | tee {{ private_key_path }}"
      register: private_key
    - name: Ensure only root can see the private key
      file:
        name: "{{ private_key_path }}"
        owner: root
        group: root
        mode: go=
    - name: Generate the public key file
      shell: "echo {{ private_key }} | wg pubkey | tee {{ public_key_path }}"
    - name: Determine the default network device
      shell: "ip route list default | awk '{print $NF}'"
      register: network_device
    - name: Enable IPv4 forward
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: yes
    - name: Write the wg config file
      template:
        src: wg-server.conf.j2
        dest: "{{ wg_conf_path }}"
    - name: Ensure port 51820/udp is open
      ufw:
        rule: allow
        port: "51820"
        proto: udp
    - name: Ensure OpenSSH is open
      ufw:
        rule: allow
        name: OpenSSH
    - name: Reload UFW
      ufw:
        state: reloaded
    - name: Ensure wg-quick is a startup service
      systemd:
        name: wg-quick@wg0.service
        enabled: yes
    - name: Ensure wg-quick is running
      systemd:
        name: wg-quick@wg0.service
        state: started
