version: "3.7"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${DOCKER_UID}
      - PGID=${DOCKER_GID}
    volumes:
      - ${JELLYFIN_CONFIG_PATH}:/config
      - ${MEDIA_PATH}:/data:ro
    ports:
      - "{{ jellyfin_port }}:{{ jellyfin_port }}"
    restart: unless-stopped
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: jellyfin-wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${DOCKER_UID}
      - PGID=${DOCKER_GID}
      - TZ=America/Denver
    ports:
      - 9096:9096/tcp
    volumes:
      - ${WIREGUARD_CONFIG_PATH}:/config/wg0.conf:ro
      - /lib/modules:/lib/modules:ro
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: jellyfin-transmission
    environment:
      - PUID=${DOCKER_UID}
      - PGID=${DOCKER_GID}
      - TZ=America/Denver
      - TRANSMISSION_WEB_HOME=/combustion-release/
    volumes:
      - ${TRANSMISSION_CONFIG_PATH}:/config
      - ${MEDIA_DL_COMPLETE_PATH}:/downloads/complete
      - ${MEDIA_DL_INCOMPLETE_PATH}:/downloads/incomplete
      - ${MEDIA_WATCH_PATH}:/watch
    restart: unless-stopped
    network_mode: "service:wireguard"
    depends_on: [ "wireguard", ]
