---
title: "m9.com"
subtitle: "Hosted on crispbox"
logo: "assets/img/m9cad.png"

header: true
footer: false

theme: default
links: []

services:
  - name: "crispbox"
    items:
      - name: Messages
        url: "http://crispbox:3238"
        logo: assets/img/messages.svg
      - name: m9cad
        logo: "assets/img/m9cad.png"
        url: "http://crispbox:3001/"
      - name: Pi-hole
        logo: "assets/img/pihole.svg"
        url: "http://crispbox:805/admin/"
      - name: Kibana
        logo: "assets/img/elastic-kibana.svg"
        url: "http://crispbox:5601"
      - name: Grafana
        url: "http://crispbox:3000"
        logo: assets/img/grafana-icon.svg
      - name: Jupyter
        url: "http://crispbox:8888"
        logo: assets/img/jupyter.svg
      - name: vnstat
        url: "http://crispbox:8685"
  - name: "rpiblack"
    items:
      - name: openmediavault
        logo: "assets/img/omv.svg"
        url: "http://rpiblack:80/"
      - name: jellyfin
        logo: "assets/img/jellyfin.svg"
        url: "http://rpiblack:8096"
