version: "3.6"
services:
  homer:
    container_name: homer
    hostname: homer
    image: b4bz/homer:latest
    restart: unless-stopped
    ports:
      - 80:8080
    volumes:
      # :ro for read-only
      - ./img:/www/assets/img:ro
      - ./config.yml:/www/assets/config.yml:ro
