
- name: Ensure the app folder exists
  file:
    path: "{{ app_path }}"
    state: directory

- name: Copy config file from the master node
  template:
    src: homer.config.j2
    dest: "{{ config_path }}"

- name: Ensure the config file exists
  file:
    path: "{{ config_path }}"
    state: file

- name: Copy the images from the master node
  copy:
    src: homer-img
    dest: "{{ app_path }}"

- name: Copy Docker Compose file
  template:
    src: docker-compose.j2
    dest: "{{ app_path }}/docker-compose.yml"

- name: stop homer
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}"
    state: absent

- name: start homer
  community.docker.docker_compose_v2:
    project_src: "{{ app_path }}"
    state: present
