version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    volumes:
      - "/srv/dev-disk-by-uuid-5a0f2275-e689-459c-b6fb-cd14264bb915/svc/navidrome:/data"
      - "/srv/dev-disk-by-uuid-5a0f2275-e689-459c-b6fb-cd14264bb915/backup/media/music:/music:ro"
