- name: Receep
  hosts: receep-hosts
  vars:
    app_path: "/app/receep"
    env_parts: "{{ app_path }}/env_parts"
    mnt_path: "{{ app_path }}/mnt"
    data_path: "{{ mnt_path }}/data"
    restic_repository_name: "receep"
    restic_backup_paths:
      - src: "{{ data_path }}"
  roles:
    - receep
    - restic
