---
# Validate wireguard_mode variable
- name: Validate wireguard_mode is defined
  fail:
    msg: "wireguard_mode variable is required but not defined"
  when: wireguard_mode is not defined

- name: Validate wireguard_mode value
  fail:
    msg: "wireguard_mode must be one of: server, client, server_final. Current value: {{ wireguard_mode }}"
  when: wireguard_mode not in ['server', 'client', 'server_final']

# Server setup tasks
- name: Server setup tasks
  include_tasks: server.yml
  when: wireguard_mode == 'server'

# Client setup tasks  
- name: Client setup tasks
  include_tasks: client.yml
  when: wireguard_mode == 'client'

# Final server configuration with client keys
- name: Final server configuration
  include_tasks: server_final.yml
  when: wireguard_mode == 'server_final'
