---
- name: Ensure the required packages are installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - wireguard
    - ufw

- name: Ensure wg-quick is not running
  systemd:
    name: wg-quick@wg0.service
    state: stopped

- name: Generate the private key file
  shell: "wg genkey | tee {{ private_key_path }}"
  register: private_key

- name: Ensure only root can see the private key
  file:
    name: "{{ private_key_path }}"
    owner: root
    group: root
    mode: go=

- name: Generate the public key file
  shell: "echo {{ private_key.stdout }} | wg pubkey | tee {{ public_key_path }}"

- name: Determine the default network device
  shell: "ip route list default | awk '{print $NF}'"
  register: network_device

- name: Enable IPv4 forward
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Write the wg config file
  template:
    src: wg-server.conf.j2
    dest: "{{ wg_conf_path }}"

- name: Ensure port 51820/udp is open
  ufw:
    rule: allow
    port: "51820"
    proto: udp

- name: Ensure OpenSSH is open
  ufw:
    rule: allow
    name: OpenSSH

- name: Reload UFW
  ufw:
    state: reloaded

- name: Copy the public key file to the master node
  fetch:
    src: "{{ public_key_path }}"
    dest: "{{ vps_public_key_path }}"
    flat: yes